project:
  type: book
  output-dir: docs

book:
  title: "Deep Learning with TensorFlow 2"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "[Getting Started with TensorFlow 2]{style=\"font-weight: bold; color: #555555\"}"
      chapters:
        - notebooks/01a-basic-workflow.qmd
        - notebooks/01b-basic-regression.ipynb
        - notebooks/01c-basic-classification.ipynb
    - part: "[Use Cases of TensorFlow 2]{style=\"font-weight: bold; color: #555555\"}"
      chapters:
        - notebooks/02a-mnist.ipynb
        - notebooks/02b-imdb.ipynb
        - notebooks/02c-reuters.ipynb
        - notebooks/02d-boston.ipynb
    - part: "[Preparing Data for TensorFlow 2]{style=\"font-weight: bold; color: #555555\"}"
      chapters: 
        - notebooks/03a-handling-text.ipynb
        - notebooks/03b-handling-images.ipynb
        - notebooks/03c-handling-time-series.ipynb
    # - part:
    #   chapters:
    #     - notebooks/04a-tf-variables-and-constants.ipynb
    #     - notebooks/04b-gradient-tapes-API.ipynb
    #     - notebooks/04c-stochastic-gradient-descent.ipynb
    #     - notebooks/04d-dense-layers.ipynb
    # - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt



